# PDF paths to process
# Can be specific files or glob patterns like "path/to/dir/*.pdf"
pdf_paths:
  - "example1.pdf"
  - "example2.pdf"

# Database settings
chroma_dir: "./chroma_db"

# Search settings
default_query: "Explain the concept of reinforcement learning."
default_k_results: 5 